# Generated by Django 3.0.7 on 2020-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200705_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sluf',
            field=models.CharField(default='', max_length=130),
        ),
    ]
